--SKLEP INTERNETOWY, SZYMON CZYZMANSKI S16772

------------1 TABELA--------------------------

--1. DLA KAZDEGO MIESIACA PODAJ LICZBE ZAMOWIEN ZLOZONYCH W TYM MIESIACU. ZADBAJ O CZYTELNA PREZENTACJE DANYCH

SELECT TO_CHAR(TO_DATE(EXTRACT(MONTH FROM DATAZLOZZAM), 'MM'), 'Month') MIESIAC, EXTRACT(YEAR FROM DATAZLOZZAM) ROK,
COUNT(ZAMOWIENIEID) LICZBA_ZAMOWIEN
FROM ZAMOWIENIE
GROUP BY EXTRACT(MONTH FROM DATAZLOZZAM), EXTRACT(YEAR FROM DATAZLOZZAM)
ORDER BY EXTRACT(MONTH FROM DATAZLOZZAM);


--2. WYPISZ ID ZAMOWIENIA, STATUS ZAMOWIENIA, DATE ZLOZENIA ZAMOWIENIA, PRZEWIDYWANA DATE DOSTARCZENIA, DATE DOSTARCZENIA 
--ORAZ NAJDLUZSZY CZAS TRWANIA WYSYLKI W DNIACH NAJDLUZEJ TRWAJACEGO W REALIZACJI ZAMOWIENIA, NIE UWZGLEDNIAJAC ZAMOWIEN ANULOWANYCH

SELECT ZAMOWIENIEID, ZAMOWIENIESTATUS, DATAZLOZZAM, PRZEWDATADOST, DATADOSTARCZENIA, FLOOR(NVL(DATADOSTARCZENIA, SYSDATE) - DATAZLOZZAM) LICZBA_DNI
FROM ZAMOWIENIE
WHERE NVL(DATADOSTARCZENIA, SYSDATE) - DATAZLOZZAM = ( SELECT MAX(NVL(DATADOSTARCZENIA, SYSDATE) - DATAZLOZZAM) FROM ZAMOWIENIE )
AND UPPER(ZAMOWIENIESTATUS) IN ('W TOKU', 'ZREALIZOWANE');

--3. WYPISZ ZA ILE ZAMOWIEN KLIENCI ZDECYDOWALI SIE NA PLATNOSC RATAMI

SELECT COUNT(*) LICZBA_PLATNOSCI_RATAMI
FROM ZAMOWIENIE
WHERE CZYRATAMI = 1;


-----------ZLACZENIA------------------------

--1. DLA KAZDEGO MIASTA POLICZ ILE JEST KLIENTOW Z DANEGO MIASTA, POSORTUJ WG LICZBY KLIENTOW MALEJACO, POZNIEJ WG NAZWY MIASTA ROSNACO

SELECT MIASTO.MIASTONAZWA, COUNT(OSOBA.OSOBAID) LICZBA_KLIENTOW
FROM OSOBA JOIN KLIENT ON OSOBA.OSOBAID = KLIENT.KLIENTID
JOIN MIASTO ON OSOBA.MIASTOID = MIASTO.MIASTOID
GROUP BY MIASTO.MIASTOID, MIASTO.MIASTONAZWA
ORDER BY LICZBA_KLIENTOW DESC, MIASTO.MIASTONAZWA;


--2. DLA KAZDEGO PRODUKTU POLICZ PRZEZ ILU KLIENTOW TEN PRODUKT BYL ZAMAWIANY, POSORTUJ WG LICZBY KLIENTOW MALEJACO, NAZWY PRODUKTU ROSNACO

SELECT PRODUKT.PRODUKTNAZWA, COUNT(DISTINCT OSOBA.OSOBAID) LICZBA_KLIENTOW
FROM OSOBA JOIN PLATNOSC ON OSOBA.OSOBAID = PLATNOSC.KLIENTID
JOIN ZAMOWIENIE ON PLATNOSC.ZAMOWIENIEID = ZAMOWIENIE.ZAMOWIENIEID
JOIN ZAMOWPROD ON ZAMOWIENIE.ZAMOWIENIEID = ZAMOWPROD.ZAMOWIENIEID
JOIN EGZEMPLARZ ON ZAMOWPROD.EGZEMPLARZID = EGZEMPLARZ.EGZEMPLARZID
JOIN PRODUKT ON EGZEMPLARZ.PRODUKTID = PRODUKT.PRODUKTID
GROUP BY PRODUKT.PRODUKTNAZWA
ORDER BY 2 DESC, 1;

--3. WYPISZ KATEGORIE NADRZEDNE DLA WSZYSTKICH POZOSTALYCH KATEGORII

SELECT PODRZ.KATEGORIANAZWA
FROM KATEGORIA PODRZ LEFT JOIN KATEGORIA NADRZ ON PODRZ.KATEGORIANADRZEDNA = NADRZ.KATEGORIAID
WHERE PODRZ.KATEGORIANADRZEDNA IS NULL;


--------------------------GRUPUJACE------------------------------------------

--1. WYPISZ LICZBE SPRZEDANYCH EGZEMPLARZY DLA KAZDEGO Z PRODUCENTOW DOSTARCZAJACYCH SWE WYROBY DO SKLEPU 
--ORAZ SUME WARTOSCI ZAKUPIONYCH TOWAROW TEGO PRODUCENTA

SELECT PRODUCENT.PRODUCENTID, PRODUCENT.PRODUCENTNAZWA, COUNT(EGZEMPLARZ.EGZEMPLARZID) LICZBA_SPRZEDANYCH_EGZEMPLARZY,
SUM(PRODUKT.CENADETALICZNA) SUMA_WARTOSCI
FROM ZAMOWIENIE JOIN ZAMOWPROD ON ZAMOWIENIE.ZAMOWIENIEID = ZAMOWPROD.ZAMOWIENIEID
JOIN EGZEMPLARZ ON ZAMOWPROD.EGZEMPLARZID = EGZEMPLARZ.EGZEMPLARZID
JOIN PRODUKT ON EGZEMPLARZ.PRODUKTID = PRODUKT.PRODUKTID
JOIN PRODUCENT ON PRODUKT.PRODUCENTID = PRODUCENT.PRODUCENTID
GROUP BY PRODUCENT.PRODUCENTID, PRODUCENT.PRODUCENTNAZWA;


--2. DLA KAZDEGO PRACOWNIKA PODAJ JEGO ID, IMIE, NAZWISKO, AKTUALNY DZIAL W KTORYM PRACUJE LUB OSTATNI W JAKIM PRACOWAL
-- ORAZ LICZBE PRZYGOTOWANYCH PRZEZ NIEGO ZAMOWIEN. POSORTUJ WG LICZBY PRZYGOOWANYCH ZAMWIEN MALEJACO, PO CZYM LEKSYKOGRAFICZNIE PO NAZWISKU I IMIENIU

SELECT PRACOWNIK.PRACOWNIKID, OSOBA.IMIE, OSOBA.NAZWISKO,
( SELECT DZ.NAZWA
  FROM ZATRUDNIENIE ZATR JOIN DZIAL DZ ON ZATR.DZIALID = DZ.DZIALID
  JOIN PRACOWNIK PRAC ON ZATR.PRACOWNIKID = PRAC.PRACOWNIKID
  WHERE PRAC.PRACOWNIKID = PRACOWNIK.PRACOWNIKID 
  AND NVL(ZATR.DATAKONCOWA, SYSDATE) = ( SELECT MAX(NVL(Z.DATAKONCOWA, SYSDATE)) 
                                         FROM ZATRUDNIENIE Z 
                                         WHERE Z.PRACOWNIKID = PRAC.PRACOWNIKID ) ) DZIAL,
COUNT(*) LICZBA_ZAMOWIEN
FROM OSOBA JOIN PRACOWNIK ON OSOBA.OSOBAID = PRACOWNIK.PRACOWNIKID
JOIN ZATRUDNIENIE ON PRACOWNIK.PRACOWNIKID = ZATRUDNIENIE.PRACOWNIKID
JOIN DZIAL ON ZATRUDNIENIE.DZIALID = DZIAL.DZIALID
JOIN ZAMOWIENIE ON PRACOWNIK.PRACOWNIKID = ZAMOWIENIE.PRACOWNIKID
GROUP BY PRACOWNIK.PRACOWNIKID, OSOBA.IMIE, OSOBA.NAZWISKO
ORDER BY LICZBA_ZAMOWIEN DESC, OSOBA.NAZWISKO, OSOBA.IMIE;


--3. PODAJ LICZBE ZAMOWIEN W KTORYCH KLIENT ZAMOWIL WIECEJ NIZ JEDEN EGZEMPLARZ PRZYNAJMNIEJ JEDNEGO PRODUKTU

SELECT SUM(COUNT(DISTINCT ZAMOWIENIE.ZAMOWIENIEID)) LICZBA_ZAMOWIEN
FROM ZAMOWIENIE JOIN ZAMOWPROD ON ZAMOWIENIE.ZAMOWIENIEID = ZAMOWPROD.ZAMOWIENIEID
JOIN EGZEMPLARZ ON ZAMOWPROD.EGZEMPLARZID = EGZEMPLARZ.EGZEMPLARZID
JOIN PRODUKT ON EGZEMPLARZ.PRODUKTID = PRODUKT.PRODUKTID
GROUP BY ZAMOWIENIE.ZAMOWIENIEID
HAVING COUNT(EGZEMPLARZ.EGZEMPLARZID) > COUNT(DISTINCT PRODUKT.PRODUKTID);


----------PODZAPYTANIA ZWYKLE--------------------

--1. WYPISZ IMIONA I NAZWISKA KLIENTOW KTORZY SREDNIO ZA SWOJE ZAMOWIENIA ZAPLACILI MNIEJ NIZ ZROBIL TO PRZECIETNY KLIENT

SELECT OSOBA.IMIE, OSOBA.NAZWISKO, ROUND(AVG(PLATNOSC.KWOTA), 2) SREDNIA_PLATNOSC_ZA_ZAMOWIENIE,
( SELECT ROUND(AVG(SR_PLAT_ZAM.SREDNIA), 2) SREDNIA
  FROM ( SELECT AVG(PLAT.KWOTA) SREDNIA
         FROM PLATNOSC PLAT
         GROUP BY PLAT.KLIENTID ) SR_PLAT_ZAM ) PRZECIETNY_KLIENT
FROM OSOBA JOIN PLATNOSC ON OSOBA.OSOBAID = PLATNOSC.KLIENTID
GROUP BY OSOBA.OSOBAID, OSOBA.IMIE, OSOBA.NAZWISKO
HAVING AVG(PLATNOSC.KWOTA) < ( SELECT AVG(SR_PLAT_ZAM.SREDNIA) SREDNIA
                               FROM ( SELECT AVG(PLAT.KWOTA) SREDNIA
                                      FROM PLATNOSC PLAT
                                      GROUP BY PLAT.KLIENTID ) SR_PLAT_ZAM ) 
ORDER BY SREDNIA_PLATNOSC_ZA_ZAMOWIENIE, OSOBA.NAZWISKO, OSOBA.IMIE;


--2. WYPISZ LICZBE KLIENTOW KTORZY PODALI MIASTO LEZACE POZA GRANICAMI POLSKI

SELECT COUNT(*) LICZBA_KLIENTOW
FROM OSOBA JOIN KLIENT ON OSOBA.OSOBAID = KLIENT.KLIENTID
WHERE OSOBA.MIASTOID IN ( SELECT MIASTO.MIASTOID FROM MIASTO 
                          WHERE MIASTO.PANSTWOID <> ( SELECT PANSTWO.PANSTWOID FROM PANSTWO
                                                      WHERE UPPER(PANSTWO.PANSTWONAZWA) = 'POLSKA' ) );


--3. WYPISZ PRACOWNIKOW KTORZY NIE SA JEDNOCZESNIE KLIENTAMI SKLEPU, UPORZADKUJ LEKSYKOGRAFICZNIE WEDLUG NAZWISK ORAZ IMION

SELECT OSOBA.OSOBAID, OSOBA.IMIE, OSOBA.NAZWISKO
FROM PRACOWNIK JOIN OSOBA ON PRACOWNIK.PRACOWNIKID = OSOBA.OSOBAID
WHERE PRACOWNIK.PRACOWNIKID NOT IN ( SELECT OS.OSOBAID FROM OSOBA OS
                                     JOIN KLIENT ON OS.OSOBAID = KLIENT.KLIENTID )
ORDER BY OSOBA.NAZWISKO, OSOBA.IMIE;


---------SKORELOWANIA--------------------

--1. WYPISZ IMIE, NAZWISKO, DATE URODZENIA, NAZWE MIASTA ORAZ ILE W SUMIE PIENIEDZY WYDALA OSOBA, KTORA DOKONALA NAJWIEKSZEJ LICZBY ZAMOWIEN.
--POSORTUJ WG NAZWISKA, IMIENIA, SUMY WYDANYCH PIENIEDZY

SELECT OSOBA.OSOBAID, OSOBA.IMIE, OSOBA.NAZWISKO
( SELECT MIASTO.MIASTONAZWA FROM OSOBA O JOIN MIASTO ON O.MIASTOID = MIASTO.MIASTOID WHERE O.OSOBAID = OSOBA.OSOBAID ) MIASTO,
( SELECT SUM(P.KWOTA) FROM PLATNOSC P JOIN OSOBA O ON O.OSOBAID = P.KLIENTID WHERE O.OSOBAID = OSOBA.OSOBAID ) SUMA_WYDANYCH_PIENIEDZY,
COUNT(DISTINCT PLATNOSC.ZAMOWIENIEID) LICZBA_ZAMOWIEN
FROM OSOBA JOIN PLATNOSC ON OSOBA.OSOBAID = PLATNOSC.KLIENTID
GROUP BY OSOBA.OSOBAID, OSOBA.IMIE, OSOBA.NAZWISKO
HAVING COUNT(DISTINCT PLATNOSC.ZAMOWIENIEID) = ( SELECT MAX(COUNT(DISTINCT PLAT.ZAMOWIENIEID))
                                                 FROM PLATNOSC PLAT 
                                                 GROUP BY PLAT.KLIENTID )
ORDER BY 3, 2, 5;


--2. WYPISZ PRACOWNIKOW SKLEPU KTORZY SA TEZ JEDNOCZESNIE JEGO KLIENTAMI, LICZBE ZAMOWIEN KTORA DOKONALI, NAZWE DZIALU W KTORYM OBECNIE PRACUJA,
--JESLI JUZ NIE PRACUJA W FIRMIE TO NAZWE DZIALU W KTORYM PRACOWALI PRZED ODEJSCIEM WRAZ Z INFORMACJA CZY PRACUJE CZY NIE,
--JESLI NIE TO PODAC DATE ODEJSCIA. POSORTOWAC MALEJACO WG LICZBY ZAMOWIEN, NASTEPNIE NAJPIERW UWZGLEDNIC TYCH KTORZY WCIAZ PRACUJA

SELECT KLIENT.KLIENTID, COUNT(DISTINCT PLATNOSC.ZAMOWIENIEID) LICZBA_ZAMOWIEN,
    (   SELECT DZ.NAZWA FROM DZIAL DZ JOIN ZATRUDNIENIE ZATR ON DZ.DZIALID = ZATR.DZIALID 
        WHERE ZATR.PRACOWNIKID = KLIENT.KLIENTID 
        AND ZATR.DATAPOCZATKOWA = ( SELECT MAX(Z.DATAPOCZATKOWA) FROM ZATRUDNIENIE Z
                                    WHERE Z.PRACOWNIKID = KLIENT.KLIENTID )   ) NAZWA_DZIALU,
    (   SELECT NVL2(Z.DATAKONCOWA, 'Data odejscia: ' || TO_CHAR(Z.DATAKONCOWA, 'DD-MM-YYYY'), 'Pracuje')
        FROM ZATRUDNIENIE Z JOIN PRACOWNIK PRAC ON Z.PRACOWNIKID = PRAC.PRACOWNIKID 
        WHERE PRAC.PRACOWNIKID = KLIENT.KLIENTID 
        AND Z.DATAPOCZATKOWA = ( SELECT MAX(ZATR.DATAPOCZATKOWA) FROM ZATRUDNIENIE ZATR 
                                 WHERE ZATR.PRACOWNIKID = KLIENT.KLIENTID )   ) CZY_PRACUJE
FROM PRACOWNIK JOIN OSOBA ON PRACOWNIK.PRACOWNIKID = OSOBA.OSOBAID
JOIN KLIENT ON OSOBA.OSOBAID = KLIENT.KLIENTID
JOIN PLATNOSC ON KLIENT.KLIENTID = PLATNOSC.KLIENTID
JOIN ZATRUDNIENIE ON PRACOWNIK.PRACOWNIKID = ZATRUDNIENIE.PRACOWNIKID
JOIN DZIAL ON ZATRUDNIENIE.DZIALID = DZIAL.DZIALID
WHERE ZATRUDNIENIE.DATAPOCZATKOWA = ( SELECT MAX(ZATR.DATAPOCZATKOWA) FROM ZATRUDNIENIE ZATR WHERE ZATR.PRACOWNIKID = PRACOWNIK.PRACOWNIKID )
GROUP BY KLIENT.KLIENTID
ORDER BY 2 DESC, 4 DESC;


--3. WYPISZ ID, IMIE, NAZWISKO, MIASTO, ILE PIENIEDZY WYDALA, ILE ZAMOWIEN ZLOZYLA ORAZ SREDNIA KWOTE ZAMOWIENIA 5 NAJBARDZIEJ DOCHODOWYCH KLIENTOW
-- POSORTUJ MALEJACO ZE WZGLEDU NA SUME WYDANYCH PIENIEDZY, LICZBE ZAMOWIEN, SREDNIA KWOTE ZAMOWIENIA ORAZ ROSNACO WEDLUG NAZWISK I IMION

SELECT OSOBA.OSOBAID, 
( SELECT OS.IMIE FROM OSOBA OS WHERE OS.OSOBAID = OSOBA.OSOBAID ) IMIE,
( SELECT OS.NAZWISKO FROM OSOBA OS WHERE OS.OSOBAID = OSOBA.OSOBAID ) NAZWISKO,
( SELECT MIASTO.MIASTONAZWA FROM MIASTO JOIN OSOBA OS ON MIASTO.MIASTOID = OS.MIASTOID WHERE OS.OSOBAID = OSOBA.OSOBAID ) MIASTO,
SUM(PLATNOSC.KWOTA) SUMA_WYDANYCH_PIENIEDZY,
COUNT(DISTINCT PLATNOSC.ZAMOWIENIEID) LICZBA_ZAMOWIEN,
ROUND(SUM(PLATNOSC.KWOTA) / COUNT(DISTINCT PLATNOSC.ZAMOWIENIEID), 2) SREDNIA_KWOTA_ZAMOWIENIA
FROM OSOBA JOIN PLATNOSC ON OSOBA.OSOBAID = PLATNOSC.KLIENTID
GROUP BY OSOBA.OSOBAID
HAVING ( SELECT COUNT(SUM(PLAT.KWOTA)) FROM OSOBA OS 
         JOIN PLATNOSC PLAT ON OS.OSOBAID = PLAT.KLIENTID
         GROUP BY OS.OSOBAID
         HAVING SUM(PLAT.KWOTA) > SUM(PLATNOSC.KWOTA) ) < 5
ORDER BY SUMA_WYDANYCH_PIENIEDZY DESC, LICZBA_ZAMOWIEN DESC, SREDNIA_KWOTA_ZAMOWIENIA DESC, NAZWISKO, IMIE;
